version: '3.6'
services: 
  jupyter:
      platform: linux/amd64
      build: .
      ports: 
          - 8888:8888
      volumes:
          - ./workspace:/home/jovyan/workspace
      command: jupyter notebook


  db:
    platform: linux/amd64
    image: postgres:14.2
    ports:
      - 5432:5432
    env_file:
      - docker.env
  